### ISSUE TITLE
summarizer_v2.py에 한번에 리턴값 반환하게 해주세요.

### ISSUE THREAD

**Issue by linkyouhj** [ossteam8/keywords#16]

**Comment by chaehuiseon** [comment]
sents= kss.split_sentences(news3)
mat, vocab_idx, idx_vocab = sent_graph(sents)
R = pagerank(mat)
topk = 3
idxs = R.argsort()[-topk:]
#keysents = [(idx, R[idx], sents[idx]) for idx in sorted(idxs)]
#for idx in sorted(idxs):
    #print(sents[idx])
keysents = [(sents[idx]) for idx in sorted(idxs)]
로 변경되었습니다. keysents로 리턴하면 됩니다.
