### ISSUE TITLE
test code들이 많이 올라와 실제 실행 파일이 무엇인지 모릅니다

### ISSUE THREAD

**Issue by namhyo01** [ossteam8/keywords#5]
test code들이 너무 많아 보기 안좋습니다

**Comment by chaehuiseon** [comment]
textrank용으로 사용된 주피터 노트북 파일은 textrank_keyword_test2.ipynb이고, summarize는 summarizer_v2.py 입니다.
완성된 키워드 추출 코드는  https://github.com/ossteam8/LDA_TextRank_keyword 로 합쳐졌습니다.
